apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devox-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/HamzaZo/backend-app-demo.git
    path: chart/backend-app
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: 1.21
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
